---
- hosts: all
  become: yes  # Ensure sudo access if needed
  vars_files:
    - vars/k8s_vars.yaml  # Corrected spelling
  roles:
    - ../roles/kubeadm  # Role name should match the one inside `roles/`

