---
- name: Install Required Packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes 
  become: yes
  loop: "{{ package_list }}"

- name: Add the Docker GPG key
  get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: "/usr/share/keyrings/docker-archive-keyring.gpg"
    mode: '0644'

- name: Add the Docker Repository
  shell: |
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
  become: yes

- name: Update the apt packages
  apt:
    update_cache: yes
  become: yes
      
- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: yes

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Download cri-dockerd
  get_url:
    url: https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.4/cri-dockerd_0.3.4.3-0.ubuntu-jammy_amd64.deb
    dest: /tmp/cri-dockerd.deb

- name: Install cri-dockerd
  apt:
    deb: /tmp/cri-dockerd.deb
  become: yes

- name: Enable cri-dockerd services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  become: yes
  loop:
    - cri-docker.service
    - cri-docker.socket

- name: Download Kubernetes GPG key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    dest: /tmp/kubernetes-key.gpg

- name: Convert and save Kubernetes GPG key
  shell: |
    gpg --dearmor < /tmp/kubernetes-key.gpg | sudo tee /etc/apt/keyrings/kubernetes-apt-keyring.gpg > /dev/null
  become: yes


- name: Write Kubernetes repository to a temporary file
  shell: |
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /" > /tmp/kubernetes.list

- name: Move Kubernetes repository file to sources.list.d
  shell: sudo mv /tmp/kubernetes.list /etc/apt/sources.list.d/kubernetes.list
  become: yes

- name: Update APT packages again
  apt:
    update_cache: yes
  become: yes

- name: Disable swap
  shell: swapoff -a
  become: yes

- name: Comment out swap entry in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)$'
    replace: '#\1'
  become: yes
 
- name: Load kernel modules
  shell: |
     modprobe overlay
     modprobe br_netfilter   
  become: yes

- name: Configure sysctl settings for Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    mode: '0644'
  become: yes

- name: Apply sysctl settings
  command: sysctl --system
  become: yes

- name: Ensure /etc/docker directory exists
  file:
    path: /etc/docker
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: yes

- name: Configure Docker daemon.json
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
    mode: '0644'
  become: yes

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
  become: yes

- name: Install Kubernetes components
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes
  become: yes
